---
new_page_extension: md
auto_deploy: false
admin_path: bearbeiten
webhook_url: 
sections:
- type: heading
  label: Vollerwieker
- type: directory
  path: "**/**"
  label: ALlles
  create: all
  match: "**/*"
- type: directory
  path: src/pages
  label: Seiten
  create: all
  match: "**/*"
- type: directory
  path: static/images
  label: Dateien
  create: all
  match: "**/*"
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
